kind: Deployment
apiVersion: apps/v1
metadata:
  name: banking-portal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-portal-ui
  template:
    metadata:
      labels:
        app: banking-portal-ui
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: banking-portal-ui
          image: banking-portal-ui:latest
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
            limits:
              memory: "5Gi"
              cpu: "2000m"
          volumeMounts:
            - name: angular-cache
              mountPath: /app/.angular
      volumes:
        - name: angular-cache
          emptyDir:
            medium: Memory